"""adiciona foreign key de daily_register em withdrawal

Revision ID: bbf925d0192d
Revises: 09f128c04484
Create Date: 2026-09-30 18:19:00.184155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf925d0192d'
down_revision = '09f128c04484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_register_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sale_daily_register', 'daily_register', ['daily_register_id'], ['id'])

    with op.batch_alter_table('withdrawal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_register_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_withdrawal_daily_register', 'daily_register', ['daily_register_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_withdrawal_daily_register', type_='foreignkey')
        batch_op.drop_column('daily_register_id')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sale_daily_register', type_='foreignkey')
        batch_op.drop_column('daily_register_id')

    # ### end Alembic commands ###
